---

- name: Combine docker container variable
  set_fact:
    automated_docker_run: "{{ automated_docker_container_default[automated_docker_container.key] | combine(automated_docker_container.value) }}"

- block: # Pre-upgrade container

  # TODO Change to use docker_container action when state: stopped is fix
  # https://github.com/ansible/ansible-modules-core/issues/4199
  - name: Stop current running container
    command: "docker stop {{ automated_docker_run.name }}"
    when: automated_docker_run.upgrade is defined and automated_docker_run.upgrade

  - name: Set container stopped name variable
    set_fact:
      automated_docker_container_stopped_name: "{{ automated_docker_run.name }}-stopped"
    when: automated_docker_run.upgrade is defined and automated_docker_run.upgrade

  - name: Rename stopped container
    command: "docker rename {{ automated_docker_run.name }} {{ automated_docker_container_stopped_name }}"
    when: automated_docker_run.upgrade is defined and automated_docker_run.upgrade

- block: # Run Docker container

  - name: Create container if not exists
    docker_container:
      name: "{{ automated_docker_run.name }}"
      hostname: "{{ automated_docker_run.hostname }}"
      image: "{{ automated_docker_run.image }}"
      restart_policy: "{{ automated_docker_run.restart_policy | default(automated_docker_container_default_restart_policy) }}"
      recreate: "{{ automated_docker_run.recreate | default(automated_docker_container_default_recreate) }}"
      pull: "{{ automated_docker_run.pull | default(automated_docker_container_default_pull) }}"
      command: "{{ automated_docker_run.command | default(omit) }}"
      published_ports: "{{ automated_docker_run.published_ports | default(omit) }}"
      exposed_ports: "{{ automated_docker_run.exposed_ports | default(omit) }}"
      links: "{{ automated_docker_run.links | default(omit) }}"
      env: "{{ automated_docker_run.environment | default(omit) }}"
      volumes: "{{ automated_docker_run.volumes | default(omit) }}"
      log_driver: "{{ automated_docker_run.log_driver | default(omit) }}"
      log_options: "{{ automated_docker_run.log_options | default(omit) }}"
      volumes_from: "{{ (automated_docker_run.upgrade is defined and automated_docker_run.upgrade) | ternary(automated_docker_container_stopped_name, omit) }}"
      state: present

  - name: Add container to inventory
    add_host:
      name: "{{ automated_docker_run.name }}"
      groups: automated_docker_containers
      ansible_connection: docker
      ansible_user: root
      ansible_docker_extra_args: "{{ automated_docker_extra_args | default(omit) }}"

- block: # Run pre-start configure on container

  - name: Check if has pre-start container tasks file
    stat:
      path: "{{ role_path }}/tasks/{{ automated_docker_run.name }}/{{ automated_docker_run.name }}_pre_start.yml"
      get_md5: no
    register: automated_docker_has_pre_start_container

  - name: Include pre-run task
    include: "{{ automated_docker_name }}/{{ automated_docker_name }}_pre_start.yml"
    when: automated_docker_has_pre_start_container.stat.exists == true

- block: # Start container

  - name: Start container
    docker_container:
      name: "{{ automated_docker_run.name }}"
      state: started

- block: # Run post-start configure on container

  - name: Check if has post-start container tasks file
    stat:
      path: "{{ role_path }}/tasks/{{ automated_docker_run.name }}/{{ automated_docker_run.name }}_post_start.yml"
      get_md5: no
    register: automated_docker_has_post_start_container

  - name: Include post-run task
    include: "{{ automated_docker_name }}/{{ automated_docker_name }}_post_start.yml"
    when: automated_docker_has_post_start_container.stat.exists == true

  tags:
    - automated-docker-run
