---
# NOTE Need to use docker command because docker registry image doesn't has python installed
# TODO Use utilities container instead of docker command

- block: # Build variable for HAProxy template

  - name: Get all server list from DNS-SD
    set_fact:
      automated_docker_haproxy_backend: "{{ lookup('dig', automated_docker_haproxy_srv_fqdn + '/SRV', 'flat=0', wantlist=True) }}"

- block: # Copy HAProxy configuration file

  - name: Create HAProxy configuration file
    template:
      src: "{{ automated_docker_haproxy_template_file }}"
      dest: "{{ automated_docker_haproxy_host_tmp_config_path }}"

  - name: Copy HAProxy configuration file to container
    command: |
      docker cp "{{ automated_docker_haproxy_host_tmp_config_path }}" \
      "{{ automated_docker_run.name }}":"{{ automated_docker_haproxy_container_config_path }}"
    notify: Check HAProxy configuration and reload HAProxy
